# Build docker image
name: Build

on:
  release:
    types: [published]

jobs:
  # docker-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Build and publish docker image
  #       uses: docker/build-push-action@v1.1.1
  #       with:
  #         repository: faforever/lua
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         tag_with_ref: true

  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build lua
        run: make \
          MYCFLAGS='-O3 -fomit-frame-pointer' \
          USERCONF=$'-DLUA_USERCONFIG=\'"$(LUA)/etc/saconfig.c"\' -DUSE_READLINE' \
          EXTRA_LIBS='-lm -ldl -lreadline -lhistory' \
          all strip

      - name: Create archive
        run: |
          export ARCHIVE=faf-lua-${GITHUB_REF#refs/*/v}-linux
          cp --parents -t $ARCHIVE bin/* include/*.h lib/*.a doc/*.1
          tar -czf $ARCHIVE.tar.gz faf-lua-linux

      - name: Upload release asset
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["faf-lua-*-linux.tar.gz"]'
